package postgres

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/google/uuid"
	"github.com/supabase-community/supabase-go"

	"github.com/MinutelyAI/minutely-api/internal/core/domain"
)

type supabaseProfileRepo struct {
	client *supabase.Client
}

func NewSupabaseProfileRepo(client *supabase.Client) domain.ProfileRepository {
	return &supabaseProfileRepo{client: client}
}

func (r *supabaseProfileRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Profile, error) {
	data, _, err := r.client.From("profiles").Select("*", "exact", false).Eq("id", id.String()).Single().Execute()
	if err != nil {
		return nil, err
	}
	
	if len(data) == 0 {
		return nil, errors.New("profile not found")
	}

	var profile domain.Profile
	if err := json.Unmarshal(data, &profile); err != nil {
		return nil, err
	}

	return &profile, nil
}

func (r *supabaseProfileRepo) Create(ctx context.Context, profile *domain.Profile) error {
	_, _, err := r.client.From("profiles").Insert(profile, false, "exact", "representation", "id").Execute()
	return err
}

func (r *supabaseProfileRepo) Update(ctx context.Context, profile *domain.Profile) error {
	_, _, err := r.client.From("profiles").Update(profile, "exact", "id").Eq("id", profile.ID.String()).Execute()
	return err
}

type supabaseMeetingRepo struct {
	client *supabase.Client
}

func NewSupabaseMeetingRepo(client *supabase.Client) domain.MeetingRepository {
	return &supabaseMeetingRepo{client: client}
}

func (r *supabaseMeetingRepo) Create(ctx context.Context, meeting *domain.Meeting) error {
	// The id will be generated by the DB. We should omit it if it's empty, or generate it here.
	if meeting.ID == uuid.Nil {
		meeting.ID = uuid.New()
	}
	
	data, _, err := r.client.From("meetings").Insert(meeting, false, "exact", "representation", "id").Execute()
	if err != nil {
		return err
	}

	if len(data) > 0 {
		// Try to unmarshal the returned data back to meeting to capture created_at etc
		var created []domain.Meeting
		if err := json.Unmarshal(data, &created); err == nil && len(created) > 0 {
			*meeting = created[0]
		}
	}

	return nil
}

func (r *supabaseMeetingRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Meeting, error) {
	data, _, err := r.client.From("meetings").Select("*", "exact", false).Eq("id", id.String()).Single().Execute()
	if err != nil {
		return nil, err
	}

	if len(data) == 0 {
		return nil, errors.New("meeting not found")
	}

	var meeting domain.Meeting
	if err := json.Unmarshal(data, &meeting); err != nil {
		return nil, err
	}

	return &meeting, nil
}

func (r *supabaseMeetingRepo) ListByUser(ctx context.Context, userID uuid.UUID) ([]*domain.Meeting, error) {
	data, _, err := r.client.From("meetings").Select("*", "exact", false).Eq("user_id", userID.String()).Execute()
	if err != nil {
		return nil, err
	}

	var meetings []*domain.Meeting
	if err := json.Unmarshal(data, &meetings); err != nil {
		return nil, err
	}

	return meetings, nil
}

func (r *supabaseMeetingRepo) ListSummaries(ctx context.Context, userID uuid.UUID) ([]*domain.MeetingSummary, error) {
	data, _, err := r.client.From("meeting_summaries").
		Select("*", "exact", false).
		Eq("user_id", userID.String()).
		Order("created_at", nil).
		Execute()
	if err != nil {
		return nil, err
	}

	var summaries []*domain.MeetingSummary
	if err := json.Unmarshal(data, &summaries); err != nil {
		return nil, err
	}

	return summaries, nil
}

func (r *supabaseMeetingRepo) Update(ctx context.Context, meeting *domain.Meeting) error {
	_, _, err := r.client.From("meetings").Update(meeting, "exact", "id").Eq("id", meeting.ID.String()).Execute()
	return err
}

func (r *supabaseMeetingRepo) GetDashboardStats(ctx context.Context, userID uuid.UUID) (*domain.DashboardStats, error) {
	// Call the Supabase RPC function 'get_dashboard_stats'
	data := r.client.Rpc("get_dashboard_stats", "", map[string]interface{}{
		"p_user_id": userID.String(),
	})

	if data == "" {
		return nil, errors.New("rpc returned empty data")
	}

	// We expect data to be a JSON string like "{\"total_meetings\": 5, ...}"
	// or directly the JSON bytes depending on the client.
	// We'll try to unmarshal it directly first.
	// Note: supabase.Rpc might return string or []byte or interface. 
	// The supabase-community/supabase-go client returns string for Rpc.
	
	var stats domain.DashboardStats
	if err := json.Unmarshal([]byte(data), &stats); err != nil {
		return nil, err
	}

	return &stats, nil
}
